from app.extensions import db

class Ingredient(db.Model):
    __tablename__ = 'ingredients'
    #NOTE - ingredient_id is generated by the database
    #FIXME - i made up this schema :)
    ingredient_id = db.Column(db.Integer, primary_key=True, nullable=False)
    ingredient_name = db.Column(db.String(64), nullable=False)
    ingredient_price = db.Column(db.Float, nullable=False)
    
    def __repr__(self):
        return f"<Ingredient {self.ingredient_id}>"

    def to_dict(self):
        return {
            "ingredient_id": self.ingredient_id,
            "ingredient_name": self.ingredient_name,
            "ingredient_price": self.ingredient_price
        }