from app.extensions import db

class MenuItem(db.Model):
    __tablename__ = 'menu_items'
    #NOTE - menu_item_id is generated by the database
    order_id = db.Column(db.Integer, db.ForeignKey('orders.order_id'), nullable=False)
    meal_type_price = db.Column(db.Float, nullable=False)
    meal_type = db.Column(db.String(32), nullable=False)
    premium_multiplier = db.Column(db.Float, nullable=False)
    total_menu_item_price = db.Column(db.Float, nullable=False)
    
    def __repr__(self):
        return f"<MenuItem {self.menu_item_id}>"

    def to_dict(self):
        return {
            "menu_item_id": self.menu_item_id,
            "order_id": self.order_id,
            "meal_type_price": self.meal_type_price,
            "meal_type": self.meal_type,
            "premium_multiplier": self.premium_multiplier,
            "total_menu_item_price": self.total_menu_item_price
        }