from app.extensions import db

class MenuItem(db.Model):
    __tablename__ = 'menu_items'
    #NOTE - menuitem_id is generated by the database
    
    menuitem_id = db.Column(db.Integer, primary_key=True, nullable=False)
    order_id = db.Column(db.Integer, db.ForeignKey('orders.order_id'), nullable=False)
    menuitem_price = db.Column(db.Float, nullable=False)
    meal_type = db.Column(db.String(32), nullable=False)
    premium_multiplier = db.Column(db.Integer, nullable=False)
    total_menuitem_price = db.Column(db.Float, nullable=False)
    
    def __repr__(self):
        return f"<MenuItem {self.menuitem_id}>"

    def to_dict(self):
        return {
            "menuitem_id": self.menuitem_id,
            "order_id": self.order_id,
            "menuitem_price": self.menuitem_price,
            "meal_type": self.meal_type,
            "premium_multiplier": self.premium_multiplier,
            "total_menuitem_price": self.total_menuitem_price
        }